server:
  port: 8080
  servlet:
    context-path: "/todoapp/api"


spring:
  application:
    name: todoapp
  datasource:
    password: SuperSecret
    url: jdbc:h2:mem:todoappdb
    username: sa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show_sql: true